### ISSUE TITLE
Non-discrete gravity

### ISSUE THREAD

**Issue by LostKin** [Mysteryem/Up_And_Down_And_All_Around#110]
Is there a way to make gravity not discrete (not only in 6 directions) but to make it a vector of xyz, that player gravity will follow?

**Comment by Mysteryem** [comment]
This is unlikely to ever happen without almost a full rewrite of the mod and even then, I'm not sure how possible it would be to do without even more significant changes to vanilla code with ASM. There are a lot of shortcuts that are available when limited to the 6 fixed directions, which keeps things a lot simpler.
