### ISSUE TITLE
The anchor items aren't appearing in the creative inventory

### ISSUE THREAD

**Issue by Roboticy3** [Mysteryem/Up_And_Down_And_All_Around#115]
I recently installed the latest version of the mod as of 4/15/2020 and loaded it up successfully through forge1.12.2-14.23.5.2779. The anchor items, which I downloaded the mod specifically for, are gone from the creative inventory. I tried installing multiple different versions to no success.

**Comment by Roboticy3** [comment]
Fix: use not enough items to access the items

**Comment by Jarfeh** [comment]
that's not a fix
