### ISSUE TITLE
World Stall w/ Speedster Heroes Mod

### ISSUE THREAD

**Issue by WenXin20** [Mysteryem/Up_And_Down_And_All_Around#65]
[Speedster Heroes](https://minecraft.curseforge.com/projects/speedster-heroes) v1.0.2
[Lucraft Core](https://minecraft.curseforge.com/projects/lucraft-core) v1.0.1
Up & Down & All Around v2.6
The world refuses to load and freezes with a 0% on the load screen.
[Error Log](http://pastebin.com/123NJYjW)

**Comment by Mysteryem** [comment]
Thanks for the report, should be fixed in the next version of UpAndDown.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Mysteryem** [comment]
v2.7 is out now, which seems to fix the issue: https://minecraft.curseforge.com/projects/up-and-down-and-all-around/files/2395193
