### ISSUE TITLE
Crash w/ Valkyrien Warfare Mod

### ISSUE THREAD

**Issue by WenXin20** [Mysteryem/Up_And_Down_And_All_Around#68]
Forge 2254
Up & Down & All Around v2.7.1
[Valkyrien Warfare](https://minecraft.curseforge.com/projects/valkyrien-warfare/files/2403101) v0.8.999 Stable
After updating this mod, I got a crash with valkyrien Warfare. The previous version, v2.7, worked fine with this mod. 
[Crash w/ Valkyrien Warfare](https://pastebin.com/VxhBtta2)

**Comment by Mysteryem** [comment]
[v2.7.1 Disables a single line of logging](https://github.com/Mysteryem/Up_And_Down_And_All_Around/commit/cb757599aa54da4ae86e932cbe8a02ecac4aaf8a), there are no other changes and I don't mess with item entities, it is definitely a coincidence.

Also, the stacktrace from the crash log only mentions Valkyrien Warfare classes, I would go and create this issue on [their tracker](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues) instead.

**Comment by WenXin20** [comment]
Ok, thanks
