### ISSUE TITLE
Crash w/ Voxels Mod

### ISSUE THREAD

**Issue by WenXin20** [Mysteryem/Up_And_Down_And_All_Around#69]
Forge 2254
Up & Down & All Around v2.7.1
[Voxels](https://minecraft.curseforge.com/projects/voxels/files/2413445) v1.0.8.2
After updating this mod, I got a crash with Voxels. The previous version, v2.7, worked fine with this mod. Though I'm not sure if the crash w/ voxels is related, but it only crashed after adding this mod as well.
[Crash w/ Voxels](https://pastebin.com/QbDDuxNX)

**Comment by Mysteryem** [comment]
This is unrelated to Up And Down, and looks like the same crash as https://github.com/capnkirok/Voxels/issues/28, please use that issue on the Voxels issue tracker.

It may be useful for the Voxels developer to see which mods are present in both your crash log and the existing one in the linked issue, so please provide them with your crash log.

As I said in the previous issue, there are basically no changes between v2.7 and v2.7.1.

**Comment by WenXin20** [comment]
Ok, thanks
