### ISSUE TITLE
License

### ISSUE THREAD

**Issue by asiekierka** [Mysteryem/Up_And_Down_And_All_Around#75]
I would like to pull request a 1.12 port of the mod, but the lack of a license makes it unclear as to what my rights are in relation to the code.

If you want to, I can suggest a license which would be good for the project.

**Comment by Mysteryem** [comment]
I have licensed it LGPL v3

**Comment by asiekierka** [comment]
That's sufficient. I'll finish the port tomorrow, thank you!

**Comment by asiekierka** [comment]
Apologies, haven't quite been able to finish it yet.
