### ISSUE TITLE
[1.12.2] All the items are "tooltip error"

### ISSUE THREAD

**Issue by Xiaminou** [Mysteryem/Up_And_Down_And_All_Around#81]
I learned about this mod at BTM Moon and wanted to try it however all items have "tooltip error" instead of names.

![2017-11-21_00 55 53](https://user-images.githubusercontent.com/8670392/33047565-c730dd1c-ce56-11e7-9078-fbc3c50e9568.png)

Logs: [fml-client-latest.txt](https://github.com/Mysteryem/Up_And_Down_And_All_Around/files/1489525/fml-client-latest.txt) and [fml-junk-earlystartup.txt](https://github.com/Mysteryem/Up_And_Down_And_All_Around/files/1489526/fml-junk-earlystartup.txt)

Minecraft: 1.12.2
Forge: 2544
Mods: [list.txt](https://github.com/Mysteryem/Up_And_Down_And_All_Around/files/1489521/list.txt)

**Comment by Mysteryem** [comment]
I honestly don't know. As you may have seen it was fine in the BTM Moon pack.

I also tried the exact same Forge, JEI and UpAndDown versions as in your modlist and have no issues.

According to the log you provided, even the ore blocks produced tooltip errors, but they don't even have any tooltips beyond what any old block has (e.g. dirt).
