### ISSUE TITLE
Baubles-CB's DepLoader was unable to download...

### ISSUE THREAD

**Issue by Kit4life** [Mysteryem/Up_And_Down_And_All_Around#88]
CB's DepLoader was unable to download required library Baubles-1.7.10-1.0.1.10.jar Check your internet connection and try restarting or download it manually from https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar and put it in your mods folder

This keeps showing up and the link is not a real link

**Comment by Mysteryem** [comment]
I don't think this had anything to do with my mod, I've never even supported 1.7.10.
