### ISSUE TITLE
This mod causing crashes when starting up the game.

### ISSUE THREAD

**Issue by IndigoAvemour** [Mysteryem/Up_And_Down_And_All_Around#91]
It took a lot of digging around to figure out which mod was causing the crashes, as every time I would disable a mod the logs point out as being the source of the problem, a different mod would be the supposed issue causing crashing. It took disabling all of the coremods and re-enabling them one by one to root out the problem, which turned out to be Up And Down And All Around, all other mods work perfectly fine. [Crash log here](https://pastebin.com/PXBgNXN0).

**Comment by Xiaminou** [comment]
It's Forge Build 1.12.2-14.23.2.2642 and higher

https://github.com/Vazkii/Botania/issues/2607

[crash-2018-04-21_13.57.42-client.txt](https://github.com/Mysteryem/Up_And_Down_And_All_Around/files/1934460/crash-2018-04-21_13.57.42-client.txt)

**Comment by steampunko** [comment]
The mod crashes on recent versions of forge.

**Comment by steampunko** [comment]
I think the mod dev pretty much gave up on this

**Comment by Mysteryem** [comment]
This should be fixed as of v2.9.0.
