### ISSUE TITLE
crash on startup.

### ISSUE THREAD

**Issue by matyklugDebbuged** [Mysteryem/Up_And_Down_And_All_Around#92]
https://pastebin.com/ebtHxXgU
forge: 14.23.4.2750
minecraft: 1.12.2
mod: 2.8.2

**Comment by thomas-williams** [comment]
I'm working on a modpack and finally went through all the mods I wanted one by one and found this was the one that was causing this same crash. It seems like it's missing some library or other mod. It happens even when the mod is the only one installed.

**Comment by matyklugDebbuged** [comment]
its happening because author changes code of soundmanager(to rotate sounds...) and forge changed soundmanager in version 14.23.2.2645, so author's code isnt compatible. just disable the code change in core mode and it should be fixed (no gurantee tho).

**Comment by thomas-williams** [comment]
Not sure exactly what you mean but if you walk me through what needs to be done I'll make a pull request here that could maybe help other people out in the future.

**Comment by matyklugDebbuged** [comment]
Sorry, typo, i meant core mod. Its that part of mod that changes others code. He mentiones SoundManager in list of modified classes. And that modification of code is the issue(i think). But i dont understand asm/reflection or how its called, so i cant help you, but i am also working on fixing it(just trying bunch of random stuff cuz i dont know what i am doing). I would probably ask at forge discord.

**Comment by Mysteryem** [comment]
This should be fixed as of v2.9.0.
