### ISSUE TITLE
Is there any intention to fix the compatibility issue with Forge?

### ISSUE THREAD

**Issue by Spider-bomb** [Mysteryem/Up_And_Down_And_All_Around#94]
I found this mod recently, looking for something a little more modern for gravity mods than starminer, and it looks very promising! However, it doesn't work with newer versions of forge, which is an issue since other mods I want to use it with don't work with the older version either. It seems like the issue is in how the mod interacts with the sound manager, or something else I'm not smart enough to figure out. Are there plans to update the mod to work with newer forge versions or am I out of luck? If there's anything I can add, like crash reports or what-have-you, please let me know.

**Comment by Mysteryem** [comment]
This should be fixed as of v2.9.0.
